# Cloud Build configuration for GotJUNK? FoundUp
# Deploys from modules/foundups/gotjunk/frontend/ to Cloud Run

steps:
  # Step 1: Build Docker image with Firebase secrets
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker build \
          --build-arg VITE_FIREBASE_API_KEY=$$VITE_FIREBASE_API_KEY \
          --build-arg VITE_FIREBASE_APP_ID=$$VITE_FIREBASE_APP_ID \
          --build-arg VITE_FIREBASE_SENDER_ID=$$VITE_FIREBASE_SENDER_ID \
          -t gcr.io/$PROJECT_ID/gotjunk:$COMMIT_SHA \
          -t gcr.io/$PROJECT_ID/gotjunk:latest \
          -f modules/foundups/gotjunk/frontend/Dockerfile \
          modules/foundups/gotjunk/frontend
    secretEnv:
      - 'VITE_FIREBASE_API_KEY'
      - 'VITE_FIREBASE_APP_ID'
      - 'VITE_FIREBASE_SENDER_ID'

  # Step 2: Push Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/gotjunk:$COMMIT_SHA'

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'gotjunk'
      - '--image=gcr.io/$PROJECT_ID/gotjunk:$COMMIT_SHA'
      - '--region=us-west1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--port=8080'
      - '--update-secrets=GEMINI_API_KEY_GOTJUNK=GEMINI_API_KEY_GOTJUNK:latest'
      - '--memory=512Mi'
      - '--cpu=1'
      - '--max-instances=10'
      - '--min-instances=0'
      - '--set-env-vars=NODE_ENV=production'

# Push image to Container Registry
images:
  - 'gcr.io/$PROJECT_ID/gotjunk:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/gotjunk:latest'

# Access secrets from Secret Manager
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/VITE_FIREBASE_API_KEY/versions/latest
      env: 'VITE_FIREBASE_API_KEY'
    - versionName: projects/$PROJECT_ID/secrets/VITE_FIREBASE_APP_ID/versions/latest
      env: 'VITE_FIREBASE_APP_ID'
    - versionName: projects/$PROJECT_ID/secrets/VITE_FIREBASE_SENDER_ID/versions/latest
      env: 'VITE_FIREBASE_SENDER_ID'

# Build options
options:
  logging: CLOUD_LOGGING_ONLY

# Timeout
timeout: '1200s'
