# -*- coding: utf-8 -*-
"""
Digital Twin Schemas - Pydantic models for structured data.

WSP Compliance:
    WSP 11: Interface Protocol (strict schemas)
    WSP 77: Agent Coordination
"""

from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional

try:
    from pydantic import BaseModel, Field
except ImportError:
    # Fallback to dataclasses if pydantic not installed
    from dataclasses import dataclass, field
    BaseModel = None


# =============================================================================
# Enums
# =============================================================================

class CommentAction(str, Enum):
    """Possible actions for a comment decision."""
    COMMENT = "comment"
    LIKE = "like"
    IGNORE = "ignore"
    HEART = "heart"


class Platform(str, Enum):
    """Supported platforms."""
    YOUTUBE = "youtube"
    LINKEDIN = "linkedin"
    X = "x"


# =============================================================================
# Pydantic Models (preferred)
# =============================================================================

if BaseModel:
    class CommentDraft(BaseModel):
        """Draft comment generated by Digital Twin."""
        platform: Platform
        context_url: str
        reply_to_id: Optional[str] = None
        text: str
        confidence: float = Field(ge=0.0, le=1.0)
        risk_flags: List[str] = Field(default_factory=list)
        retrieved_snippets: List[str] = Field(default_factory=list)

    class CommentDecision(BaseModel):
        """Decision on whether/how to engage."""
        should_comment: bool
        action: CommentAction
        reason: str
        suggested_text: Optional[str] = None
        cooldown_s: int = 300
        confidence: float = Field(ge=0.0, le=1.0)

    class ToolStep(BaseModel):
        """Single step in a tool plan."""
        tool: str
        action: str
        args: Dict[str, Any] = Field(default_factory=dict)

    class ToolPlan(BaseModel):
        """Plan for tool execution."""
        steps: List[ToolStep]
        stop_conditions: List[str] = Field(default_factory=list)
        rollback: List[ToolStep] = Field(default_factory=list)

    class TrajectoryEvent(BaseModel):
        """Single event in trajectory log (training data)."""
        ts: datetime = Field(default_factory=datetime.now)
        video_id: Optional[str] = None
        thread_id: Optional[str] = None
        context: Dict[str, Any] = Field(default_factory=dict)
        retrieved_snippets: List[str] = Field(default_factory=list)
        draft: Optional[CommentDraft] = None
        decision: Optional[CommentDecision] = None
        toolplan: Optional[ToolPlan] = None
        tool_result: Optional[Dict[str, Any]] = None
        error: Optional[str] = None

    class VoiceMemoryResult(BaseModel):
        """Result from voice memory query."""
        text: str
        source_id: str
        source_type: str  # "comment" or "transcript"
        timestamp: Optional[float] = None
        video_id: Optional[str] = None
        score: float

    class StyleViolation(BaseModel):
        """Style rule violation."""
        rule: str
        message: str
        severity: str = "warning"  # "warning" or "error"

else:
    # Fallback dataclass versions
    from dataclasses import dataclass, field as dc_field
    
    @dataclass
    class CommentDraft:
        platform: str
        context_url: str
        text: str
        confidence: float
        reply_to_id: Optional[str] = None
        risk_flags: List[str] = dc_field(default_factory=list)
        retrieved_snippets: List[str] = dc_field(default_factory=list)

    @dataclass
    class CommentDecision:
        should_comment: bool
        action: str
        reason: str
        confidence: float
        suggested_text: Optional[str] = None
        cooldown_s: int = 300

    @dataclass
    class ToolStep:
        tool: str
        action: str
        args: Dict[str, Any] = dc_field(default_factory=dict)

    @dataclass
    class ToolPlan:
        steps: List[ToolStep] = dc_field(default_factory=list)
        stop_conditions: List[str] = dc_field(default_factory=list)
        rollback: List[ToolStep] = dc_field(default_factory=list)

    @dataclass
    class TrajectoryEvent:
        ts: datetime = dc_field(default_factory=datetime.now)
        video_id: Optional[str] = None
        thread_id: Optional[str] = None
        context: Dict[str, Any] = dc_field(default_factory=dict)
        retrieved_snippets: List[str] = dc_field(default_factory=list)
        draft: Optional[CommentDraft] = None
        decision: Optional[CommentDecision] = None
        toolplan: Optional[ToolPlan] = None
        tool_result: Optional[Dict[str, Any]] = None
        error: Optional[str] = None

    @dataclass
    class VoiceMemoryResult:
        text: str
        source_id: str
        source_type: str
        score: float
        timestamp: Optional[float] = None
        video_id: Optional[str] = None

    @dataclass
    class StyleViolation:
        rule: str
        message: str
        severity: str = "warning"
